Assignment 1: Flip Random Cards
jawidan/Matchismo pull request #1
Opened 2024-05-28 12:59 UTC by jawidan

Added randomly selecting cards from Playing Cards deck feature.

2024-05-28 15:27 UTC, khaletska requested changes

2024-05-28 15:27 UTC, khaletska commented on Matchismo/Model/Card/Card.h
> +#import <Foundation/Foundation.h>
Use @import over #import if it is possible

2024-05-28 15:27 UTC, khaletska commented on Matchismo/Model/Deck/Deck.m
> +    if (!_cards) {
When checking whether the object exists, compare it to nil

2024-05-28 15:27 UTC, khaletska commented on Matchismo/Model/Deck/Deck.m
> +        _cards = [[NSMutableArray alloc] init];
Prefer new over alloc+init

2024-05-28 15:27 UTC, khaletska commented on Matchismo/ViewController.m
> +    self.deck = [[PlayingCardDeck alloc] init];
Prefer new over alloc+init

2024-05-28 15:27 UTC, khaletska commented on Matchismo/ViewController.m
> +    PlayingCard *randomCard = (PlayingCard *)[self.deck drawRandomCard];
Did you read the [assignment](https://drive.google.com/drive/u/1/folders/1yoBo_pjdzNq6nx2_0d42x6TQ8gKj0PZp)? Your application should come up showing the back of the card, should flip back and forth every time and should also have counter at the left bottom.

2024-05-29 07:17 UTC, eduardzurin requested changes
I agree with all the comments above. Also, could you please change the card button title color to black as it was done in the lecture? You can do this in the storyboard.

2024-05-29 09:57 UTC, eduardzurin commented on Matchismo/ViewController.m
> +    self.flipCount++;
Let's use self.flipCount += 1 here 🙏

2024-05-29 10:03 UTC, eduardzurin approved these changes
Looks good to me now!

2024-05-29 10:25 UTC, khaletska requested changes
Make some minor style changes please, otherwise all good 👍

2024-05-29 10:25 UTC, khaletska commented on Matchismo/Model/Deck/Deck.m
> +    if (!_cards) _cards = [[NSMutableArray alloc]init];
When checking whether the object exists, compare it to nil

2024-05-29 10:25 UTC, khaletska commented on Matchismo/Model/Deck/Deck.m
> +    if (!_cards) _cards = [[NSMutableArray alloc]init];
Prefer new over alloc+init

2024-05-29 10:25 UTC, khaletska commented on Matchismo/ViewController.m
> +            [sender setBackgroundImage:[UIImage imageNamed:@"blank card hi-res"] forState:UIControlStateNormal];
Image can be renamed to "cardfront" for consistency (since you have cardback)

2024-05-29 10:25 UTC, khaletska commented on Matchismo/ViewController.m
> +- (void)showCardBack:(UIButton *)button {
And if you have showCardBack method, could also make showCardFront

2024-05-29 10:56 UTC, khaletska approved these changes

2024-05-29 10:57 UTC, merged